name: example
description: example
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dynamic_forms:
    git:
      url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
      path: packages/dynamic_forms

dev_dependencies:
  build_runner: ^1.0.0
  dynamic_forms_generator:
    git:
      url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
      path: packages/dynamic_forms_generator
