targets:
  $default:
    builders:
      dynamic_forms_generator:dynamicFormsBuilder:
        options:
          default_imports:
            - "package:flutter_dynamic_forms_components/flutter_dynamic_forms_components.dart"