# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  dynamicFormsBuilder:
    import: "package:dynamic_forms_generator/dynamic_forms_generator.dart"
    builder_factories: ["dynamicFormsBuilder"]
    build_extensions: {".yaml": [".g.dart", "_model.g.dart"]}
    build_to: source
    auto_apply: root_package
    defaults: 
      options:
        key1: "value1"
        key2: "value2"