name: expression_language
description: Library for parsing and evaluating simple expression language with additional references
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  petitparser: ^2.1.1
  rational: ^0.3.0

dev_dependencies:
  test: ^1.6.3
  test_coverage: ^0.3.0+1
  gherkin: ^0.0.4